language: elixir
elixir:
  - 1.5.0
otp_release:
  - 20.0
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
addons:
  - postgresql: '9.4'
env:
  - MIX_ENV=test
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
notifications:
  recipients:
    - serneum@gmail.com
    - david.a.shah@gmail.com
jobs:
  include:
    - stage: lint
      script:
        - mix credo
    - stage: test
      script:
        - mix ecto.setup
        - mix test
